# Generated by Django 4.2.5 on 2023-09-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_board3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board3',
            name='user',
        ),
    ]
